version: '3.3'
services:
  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'quiz'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: '0987654321'
    ports:
      - '3312:3306'
    volumes:
      - quiz:/var/lib/mysql
volumes:
  quiz:
